### ISSUE TITLE
Compability for/update to Sanity v3

### ISSUE THREAD

**Issue by pascalwengerter** [hdoro/sanity-plugin-social-preview#6]
Seeing that the last activity in the repo is ~2 years ago and Sanity had a big v3 release last fall, I was wondering whether the code will eventually receive a refurbish/work with it?

**Comment by Umayarz18** [comment]
@pascalwengerter I've also been looking forward to v3 for this plugin and it looks like there's a [branch](https://github.com/hdoro/sanity-plugin-social-preview/tree/sanity-v3) already in the works, 😄

**Comment by pascalwengerter** [comment]
> @pascalwengerter I've also been looking forward to v3 for this plugin and it looks like there's a [branch](https://github.com/hdoro/sanity-plugin-social-preview/tree/sanity-v3) already in the works, 😄

Awesome, thanks for the hint! Will talk to the author of this library next week, so might inquire about it there as well :)

**Comment by hdoro** [comment]
Hey @pascalwengerter , long time no see 😝 

I've just published `v1.1.0` with compatibility for Sanity v3 - let me know if you have any questions 🙌

**Comment by marcobarbosa** [comment]
I'm getting:

>error ./node_modules/.pnpm/sanity-plugin-social-preview@1.1.0_react-dom@18.2.0_react@18.2.0_sanity@3.14.0_styled-components@5.3.11/node_modules/sanity-plugin-social-preview/lib/index.esm.js
Module parse failed: 'import' and 'export' may appear only with 'sourceType: module' (1:1674)

I've used `pnpm` to install it and added the import as described in the documentation:
`import { SocialPreview } from 'sanity-plugin-social-preview'`

Any ideas @hdoro ?

**Comment by AymericWilke** [comment]
> I'm getting:
> 
> > error ./node_modules/.pnpm/sanity-plugin-social-preview@1.1.0_react-dom@18.2.0_react@18.2.0_sanity@3.14.0_styled-components@5.3.11/node_modules/sanity-plugin-social-preview/lib/index.esm.js
> > Module parse failed: 'import' and 'export' may appear only with 'sourceType: module' (1:1674)
> 
> I've used `pnpm` to install it and added the import as described in the documentation: `import { SocialPreview } from 'sanity-plugin-social-preview'`
> 
> Any ideas @hdoro ?

Same here…
